### ISSUE TITLE
STM3 CubeIde project Issue

### ISSUE THREAD

**Issue by SHINJUNGWOO** [tinymlcontest/tinyml_contest2022_demo_evaluation#2]
As I tried to work on validating the model with a framework other than X-CUBE-AI on board

I could not find any .cproject file. So stm32 cube IDE could not recognize the folder as a project.

If I tried to get the folder as a project by cube mx there was some error if I generate code

Main Config: These peripherals still have some not configured or wrong parameter values: [STMicroelectronics.X-CUBE-AI.7.2.0]

If I generate the code, some of the code in main.c has been erased due to ignoring remark of /* USER CODE BEGIN ~*/
/* USER CODE END ~*/

Then I tried to exchange the main.c as original main.c that has not been erased. After adding my model and weights, other parameters by Model_Init() and aiRun(input,result)

validation.py those not work, it just stops on line 46 while ser.in_waiting < 5:

even if I remark Model_Init() and aiRun(input,result) it acts same I think we have some error on validation.py and TEST_OwnModel project

I have set all pip installs and serial com port, baud rate

**Comment by tinymlcontest** [comment]
The question was also asked by email. The answer has been sent.
